### ISSUE TITLE
Reporte de Ejercicios de Hilos

### ISSUE THREAD

**Issue by AmeliReyesHernandez** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-j-a-k#1]
[PRACTICA 7 Reporte de Ejercicios de Hilos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-equipo-j-a-k/files/15124330/PRACTICA.7.Reporte.de.Ejercicios.de.Hilos.pdf)

**Comment by SandyMarissaGs** [comment]
De acuerdo a la rúbrica obtuviste el 20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
